"""Build a compact, independently compilable arXiv source package."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIGURES = (
    ROOT / "results" / "long_50k" / "figures" / "architecture.png",
    ROOT / "results" / "long_50k" / "figures" / "final_loss_by_condition.png",
    ROOT / "results" / "long_50k" / "figures" / "parameter_efficiency.png",
    ROOT / "results" / "rank_sweep" / "figures" / "rank_vs_extra_parameters.png",
    ROOT / "results" / "secondary" / "figures" / "robustness_final_loss.png",
    ROOT / "results" / "long_50k" / "mechanism" / "output_to_input_grad_ratio.png",
    ROOT / "results" / "long_50k" / "mechanism" / "input_output_grad_cosine.png",
    ROOT / "results" / "long_50k" / "mechanism" / "input_output_correction_cosine.png",
    ROOT / "results" / "long_50k" / "embedding_eval" / "figures" / "neighbor_cosine.png",
    ROOT / "results" / "long_50k" / "embedding_eval" / "figures" / "neighbor_agreement.png",
)


def build_package(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    generated_dir = output_dir / "generated"
    figures_dir = output_dir / "figures"
    generated_dir.mkdir(exist_ok=True)
    figures_dir.mkdir(exist_ok=True)

    main = (ROOT / "paper" / "main.tex").read_text()
    main = main.replace(
        r"\graphicspath{{../results/long_50k/figures/}{../results/rank_sweep/figures/}{../results/secondary/figures/}{../results/long_50k/mechanism/}{../results/long_50k/embedding_eval/figures/}}",
        r"\graphicspath{{figures/}}",
    )
    (output_dir / "main.tex").write_text(main)
    shutil.copy2(ROOT / "paper" / "references.bib", output_dir / "references.bib")

    for table in ("primary_table.tex", "rank_table.tex", "mechanism_table.tex", "secondary_table.tex", "intervention_table.tex", "result_macros.tex"):
        shutil.copy2(ROOT / "paper" / "generated" / table, generated_dir / table)
    for source in FIGURES:
        if not source.exists():
            raise SystemExit(f"missing paper figure; run paper/generate_figures.py: {source}")
        shutil.copy2(source, figures_dir / source.name)

    readme = (
        "# arXiv source package\n\n"
        "This package is generated by paper/package_arxiv.py. It is a compact,\n"
        "independently compilable snapshot of the manuscript, generated tables,\n"
        "and referenced figures. All reported values come from the checked-in\n"
        "cloud-study aggregates and compact raw artifacts.\n\n"
        "Compile with:\n\n"
        "    tectonic --keep-logs main.tex\n"
    )
    (output_dir / "README.md").write_text(readme)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=ROOT / "arxiv")
    args = parser.parse_args()
    build_package(args.output_dir)


if __name__ == "__main__":
    main()
