"""Build a compact, independently compilable arXiv source package."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIGURES = (
    ROOT / "results" / "primary" / "figures" / "final_loss_by_condition.png",
    ROOT / "results" / "primary" / "figures" / "parameter_efficiency.png",
)


def build_package(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    generated_dir = output_dir / "generated"
    figures_dir = output_dir / "figures"
    generated_dir.mkdir(exist_ok=True)
    figures_dir.mkdir(exist_ok=True)

    main = (ROOT / "paper" / "main.tex").read_text()
    main = main.replace(
        r"\graphicspath{{../results/primary/figures/}{../results/rank_sweep/figures/}}",
        r"\graphicspath{{figures/}}",
    )
    (output_dir / "main.tex").write_text(main)
    shutil.copy2(ROOT / "paper" / "references.bib", output_dir / "references.bib")

    for table in ("primary_table.tex", "rank_table.tex", "result_macros.tex"):
        shutil.copy2(ROOT / "paper" / "generated" / table, generated_dir / table)
    for source in FIGURES:
        shutil.copy2(source, figures_dir / source.name)

    readme = (
        "# arXiv source package\n\n"
        "This package is generated by paper/package_arxiv.py. It is a compact,\n"
        "independently compilable snapshot of the manuscript and its referenced\n"
        "figures. The current snapshot is explicitly provisional: its tables use\n"
        "the preliminary aggregates checked into the repository. Regenerate it\n"
        "after the final cloud studies before submission.\n\n"
        "Compile with:\n\n"
        "    tectonic --keep-logs main.tex\n"
    )
    (output_dir / "README.md").write_text(readme)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=ROOT / "arxiv")
    args = parser.parse_args()
    build_package(args.output_dir)


if __name__ == "__main__":
    main()
